# Generated by Django 5.0.4 on 2024-04-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='E_mart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CHILD', 'child'), ('MEN', 'men'), ('WOMEN', 'women'), ('HOME', 'home'), ('KITCHEN', 'kitchen')], max_length=10)),
                ('product_name', models.CharField(max_length=20)),
                ('product_price', models.FloatField()),
                ('product_quantity', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('ONLINE', 'online'), ('CASH ON DELIVERY', 'cash on delivery')], max_length=20)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
